---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: fauna-go-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-go
      branch: pipeline-fixes
      private_key: ((github-ssh-key))
      paths:
        - version

jobs:
  - name: set-self
    plan:
      - get: fauna-go-repository
        trigger: true
      - set_pipeline: self
        file: fauna-go-repository/concourse/pipeline.yml

  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-go-repository
        passed:
          - set-self

      - task: set-slack-message
        file: fauna-go-repository/concourse/tasks/slack-message.yml

      - put: fauna-go-repository
        params:
          repository: fauna-go-repository
          # use contents of version file
          tag: fauna-go-repository/version
          tag_prefix: v
          only_tag: true
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

