
---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: busybox
    tag: latest

inputs:
  - name: fauna-go-repository

outputs:
  - name: slack-message

run:
  path: ./fauna-go-repository/concourse/scripts/slack-message.sh

