---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: karlkfi/concourse-dcind

inputs:
  - name: fauna-go-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      # start containers
      docker-compose -f fauna-go-repository/tests/docker-compose-tests.yml run go-311
      # stop and remove containers
      docker-compose -f fauna-go-repository/tests/docker-compose-tests.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)

